### ISSUE TITLE
Blazor

### ISSUE THREAD

**Issue by IeuanWalker** [elmahio/netStack.js#8]
Any plans to create a blazor component for this?

**Comment by ThomasArdal** [comment]
That is not something I have thought of. But sounds like a nice little component. I'm not a Blazor expert, though. Can this be wrapped in a component somehow? We want to remove the dependency on jQuery anyway. So, maybe that helps.

I guess you are thinking about something like this? https://blog.elmah.io/wrapping-javascript-libraries-in-blazor-webassembly-wasm/

**Comment by IeuanWalker** [comment]
@ThomasArdal thanks that article might help me.

Im only just getting into blazor and migrating one of our sites over too it, so I'm not too familiar with it myself either.

The app currently just displays the raw stacktrace so found this library and struggling to get it to work with blazor atm.

**Comment by ThomasArdal** [comment]
I'm definitely not the right person to help with the wrapper. And since we don't have any concrete plans on migrating this to Blazor, I'll go ahead and close the issue. I do know that Kristoffer Strube (the guy who wrote that post) has a range of repositories on GitHub where he wraps various JavaScript APIs. So maybe there is something to get you further there: https://github.com/KristofferStrube?tab=repositories

**Comment by ThomasArdal** [comment]
@IeuanWalker There's a new version that removes the dependency of jQuery. Maybe it's easier for you to wrap the source as a Blazor component now.

**Comment by ThomasArdal** [comment]
@IeuanWalker I also tested it. Works great now:

![image](https://github.com/user-attachments/assets/9da78941-41c8-4757-94b2-f34db794f3ce)

**Comment by IeuanWalker** [comment]
@ThomasArdal awesome, will give it a go
